# Generated by Django 5.0.4 on 2024-06-02 14:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PharmaH', '0002_administrator'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine_name', models.CharField(max_length=100)),
                ('manager_id', models.CharField(default=None, max_length=500)),
            ],
        ),
        migrations.AddField(
            model_name='manager',
            name='priv_key',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AddField(
            model_name='manager',
            name='priv_key_2',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AddField(
            model_name='manager',
            name='pub_key',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='component',
            name='cost',
            field=models.CharField(default=None, max_length=500),
        ),
        migrations.AlterField(
            model_name='component',
            name='quantity',
            field=models.CharField(default=None, max_length=500),
        ),
        migrations.CreateModel(
            name='Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('quantity', models.CharField(default=None, max_length=500)),
                ('cost', models.CharField(default=None, max_length=500)),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PharmaH.manager')),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PharmaH.medicine')),
            ],
        ),
        migrations.AddField(
            model_name='component',
            name='medicine',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='PharmaH.medicine'),
        ),
    ]
